services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-price-tracker-n8n
    ports:
      - '5678:5678'
    environment:
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_custom:/home/node/.n8n/custom
    restart: unless-stopped

volumes:
  n8n_data:
  n8n_custom:
