services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-price-tracker-n8n
    ports:
      - '5678:5678'
    environment:
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
